version: "3.8"

services:

  rabbitmq1:
    build: .
    image: rabbitmq-cluster
    container_name: rabbitmq-cluster-n1
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq2:
    build: .
    image: rabbitmq-cluster
    container_name: rabbitmq-cluster-n2
    hostname: rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"

  rabbitmq3:
    build: .
    image: rabbitmq-cluster
    container_name: rabbitmq-cluster-n3
    hostname: rabbitmq3
    ports:
      - "5674:5672"
      - "15674:15672"
