version: "3.8"
services:
  queue1:
    build: .
      container_name: rabbitmq_1
      hostname: rabbitmq-cluster-node-1
      ports:
        - "5672:5672"
        - "15672:15672"
  queue2:
    build: .
      container_name: rabbitmq_2
      hostname: rabbitmq-cluster-node-2
      ports:
        - "5672:5672"
        - "15672:15672"
  queue3:
    build: .
      container_name: rabbitmq_3
      hostname: rabbitmq-cluster-node-3
      ports:
        - "5672:5672"
        - "15672:15672"
